### ISSUE TITLE
TypeError: \>\ not supported between instances of \float\ and \NoneType\

### ISSUE THREAD

**Issue by acomick** [smacke/ffsubsync#102] opened 2020-09-05 16:08 UTC
**Environment (please complete the following information):**
 - OS: Windows Server 2019 Datacenter (with desktop experience)
 - python version: Python 3.8.5
 - subsync version: Embedded in latest version of Bazaar (0.9.0.2)

**Describe the bug**
After sub download in Bazarr, an error is thrown when calling the synchronization of the service. Appears to happen for all requests

**To Reproduce**
Download a subtitle in Bazarr with the synchronize subtitle option selected

**Expected behavior**
A successful run of the subsync process

**Output**
BAZARR an exception occurs during the synchronization process for this subtitles \\nas.domain.net\nas\media\TV\The Dukes of Hazzard\The Dukes of Hazzard Season 1\The Dukes of Hazzard - S01E08 - The Big Heist WEBRip-1080p.en.srt
Traceback (most recent call last):
 File "p:\\apps\\bazarr\\bazarr\\subsyncer.py", line 46, in sync
  result = run(self.args)
 File "p:\\apps\\bazarr\\bazarr\\../libs\\ffsubsync\\ffsubsync.py", line 275, in run
  reference_pipe.fit(args.reference)
 File "p:\\apps\\bazarr\\bazarr\\../libs\\ffsubsync\\sklearn_shim.py", line 214, in fit
  self._final_estimator.fit(Xt, y, **fit_params)
 File "p:\\apps\\bazarr\\bazarr\\../libs\\ffsubsync\\speech_transformers.py", line 236, in fit
  if simple_progress + newstuff > total_duration:
TypeError: \>\ not supported between instances of \float\ and \NoneType\

**Additional context**
Reported issue in the Bazaar discord, after speaking with morpheus65535, he recommended opening a issue on this repository for further investigation

**Comment by smacke** [comment] 2020-09-05 18:08
@acomick thanks for filing an issue. Since I can repro this by deleting ffprobe, I think the problem is that ffprobe isn't on the path for some reason; however, I should have written the code to be robust to this case. Should be fixed in 625161b as well as in the latest release (0.4.7), please lmk if not!

@morpheus65535 thanks for directing acomick here; this should be fixed now.

**Closed by smacke** 2020-09-05 18:08 UTC
Labels: bug

**Comment by acomick** [comment] 2020-09-05 18:57
Great, thank you. After updating the file, I now get a different error.
`Traceback (most recent call last):
 File "p:\\apps\\bazarr\\bazarr\\subsyncer.py", line 44, in sync
  parser = make_parser()
 File "p:\\apps\\bazarr\\bazarr\\../libs\\ffsubsync\\ffsubsync.py", line 380, in make_parser
  add_cli_only_args(parser)
 File "p:\\apps\\bazarr\\bazarr\\../libs\\ffsubsync\\ffsubsync.py", line 331, in add_cli_only_args
  version=\{package} {version}\.format(package=__package__, version=get_version()))
 File "p:\\apps\\bazarr\\bazarr\\../libs\\ffsubsync\\version.py", line 11, in get_version
  with open(os.path.join(os.environ[SUBSYNC_RESOURCES_ENV_MAGIC], \__version__\)) as f:
 File "P:\\Apps\\Bazarr\\WinPython\\python-3.8.0\\lib\\os.py", line 673, in __getitem__
  raise KeyError(key) from None
KeyError: \ffsubsync_resources_xj48gjdkl340\`

Does the ffprobe binary need to be added to my path variable?

**Comment by smacke** [comment] 2020-09-05 19:22
I don't think that's the problem; we use versioneer to compute the version string (makes it easy to integrate w/ git tags), but I guess that causes things to break when not using pip to manage ffsubsync. If you replace the line `__version__ = get_versions()['version']` with `__version__ = 0.4.7` in the file `version.py` it should work hopefully.

**Comment by acomick** [comment] 2020-09-05 19:53
That appears to have done the trick, thanks a ton! Now my father will stop calling me whenever the subtitles are missynced when he wants to watch. I appreciate the help

**Comment by smacke** [comment] 2020-09-06 04:11
Glad it worked!

**Comment by morpheus65535** [comment] 2020-09-06 12:23
@smacke thanks for fixing this!

TBH, I've completely commented out [those lines](https://github.com/smacke/ffsubsync/blob/master/ffsubsync/ffsubsync.py#L330-L331) in Bazarr source to prevent the version issue. ;-)

**Comment by smacke** [comment] 2020-09-13 03:02
@morpheus65535 no problem! Btw, if you are interested, feel free to send me a list of changes you make when embedding in Bazarr, and I'd be happy to make a `bazarr-sanitize` script or something and keep it up to date so that you don't need to worry about future changes breaking.

**Comment by morpheus65535** [comment] 2020-09-13 12:27
@smacke thanks but that's the only thing I had to modify to be able to import ffsubsync without having it installed through PIP.

**Comment by smacke** [comment] 2020-09-23 03:27
@morpheus65535 gotcha, good to know!
